ARG CUDA_VERSION=12.0.0
FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-server \
    build-essential \
    git \
    wget \
    curl \
    sudo \
    locales \
    vim \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ロケール設定
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# CUDA環境変数
ENV PATH=/usr/local/cuda/bin:$PATH \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

RUN mkdir /var/run/sshd

COPY entrypoint.sh /entrypoint.sh

ENV SSH_USER=sshuser
ENV SSH_UID=2000
ENV SSH_GROUP=sshgroup
ENV SSH_GID=2000
ENV SSH_PASSWORD_ENABLED=no
ENV SSH_PASSWORD_VALUE=
ENV SSH_GRANT_SUDO=nopass
ENV SSH_PUBLIC_KEY=

EXPOSE 22

CMD ["/entrypoint.sh"]
