FROM debian:bookworm-slim

RUN echo '#!/bin/sh\nexit 101' > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-server \
    sudo \
    curl \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN rm -f /usr/sbin/policy-rc.d

RUN mkdir /var/run/sshd

COPY entrypoint.sh /entrypoint.sh

ENV SSH_USER=sshuser
ENV SSH_UID=2000
ENV SSH_GROUP=sshgroup
ENV SSH_GID=2000
ENV SSH_PASSWORD_ENABLED=no
ENV SSH_PASSWORD_VALUE=
ENV SSH_GRANT_SUDO=nopass
ENV SSH_PUBLIC_KEY=

EXPOSE 22

CMD ["/entrypoint.sh"]
